### ISSUE TITLE
missing some stl and step files for the astroberry all in one box

### ISSUE THREAD

**Issue by ardupadawan** [OpenAstroTech/OpenAstroTracker-Addons#3]
missing stl and step files for the 6-jack Decora keystone insert and the arduino buttons
if someone have them, could he add it ?

**Comment by CTetford** [comment]
Those are standard decora inserts you can buy, usually for $2-3 or so. I never modelled them. You might be able to get a file from grabcad.com and try to print it, I'm not sure how it would turn out though.
