### ISSUE TITLE
Guide for mounting the Bottom Mounted MKS & LCD Case

### ISSUE THREAD

**Issue by SchmidL** [OpenAstroTech/OpenAstroTracker-Addons#6]
Hi - just printed all the parts for the case and hoped that it's clear when i get the parts in my hand.
Unfortunately I'm still puzzled... Is there already some mounting and wiring examples available? I couldn't find anything in reddit and the wiki. Would be really helpful!

Thank you!

**Comment by intercipere** [comment]
Check this page: https://wiki.openastrotech.com/en/OpenAstroTracker/Enclosures/Bottom_Mounted_MKS_Case

Some descriptions are missing, but I think it should be clear

**Comment by SchmidL** [comment]
Perfect! When I checked the enclosure-page then I just got rerouted to the github page. Perfect! So then just the mounting is missing. But i will try to figure it out ;)
